language: node_js
node_js:
- '4'
- 'node'
sudo: false
services:
- docker
- mongodb
script:
- npm run bootstrap
- npm test
cache:
  directories:
    - node_modules
    - demo/portal/node_modules
    - demo/mobile/node_modules
    - packages/workflow-angular/node_modules
    - packages/workorder-angular/node_modules
