language: node_js
node_js:
- '4'
- 'node'
sudo: false
services:
- docker
- mongodb
script:
- npm run bootstrapCI
- npm run testCI
cache:
  directories:
    - node_modules
    - demo/portal/node_modules
    - demo/mobile/node_modules
    - packages/workflow-angular/node_modules
    - packages/workorder-angular/node_modules
    - packages/sync/node_modules
    - packages/vehicle-inspection/node_modules
    - packages/wfm/node_modules
